### ISSUE TITLE
WSS : OP : JOIN_ROOM

### ISSUE THREAD

**Issue by theRemix** [GomaGames/transmission#14]
@asolidum When `op : "JOIN_ROOM"` is received:

there will be a `payload` with the value of the room code, ex : `XLRT`

- search through map of created rooms, for matching room code `XLRT`
- if not found
    - send `*client` an `op : "JOIN_ROOM_ERROR", payload : "Invalid Room Code"`
- if found
    - set `room.Player2` to the current `*client`
    - send `*client` an `op : "PLAYER_JOINED"`, with no payload
    - send `room.Player1` an `op : "PLAYER_JOINED"`, with no payload

[Op Code Reference](https://github.com/GomaGames/transmission/wiki/OP-Codes)

**Comment by asolidum** [comment]
@theRemix  What should be done if 2 players already have joined the room and another player attempts to join?

{ op : "JOIN_ROOM_ERROR", payload : "Room Full" } ?
