### ISSUE TITLE
Animation0: Estimate Asset Sizes

### ISSUE THREAD

**Issue by kellishouts** [GomaGames/transmission#41]
- [ ] Run the app, and take a screenshot of the game play view in *mobile* … lets say iphone6? or 7? size (whichever is more common, i have no idea!). Attach screenshot.

I need to give you and adrian (who is doing all the arts) specifics on dimensions for items.

![image](https://user-images.githubusercontent.com/1865400/35479065-47ef49e0-03a2-11e8-9a77-b1b8f0336e02.png)

- [ ] Then, based on this mockup, and referencing the _actual rendered app at 100% for iPhone_ which if you inspect, should poop out some real dimensions, can you estimate for me pixel dimensions of rendered sizes for the things boxed in red?
  - [ ] Total Screen Size (at most common iPhone dimensions)
  - [ ] Character Size
  - [ ] Attack Weapon Size
  - [ ] Gold Size
  - [ ] Heart Size
  - [ ] Tiny 'Cost' Gold Size
  - [ ] Weapon Size in Button.

**Comment by theRemix** [comment]
Total Screen Size : 375 x 667
