### ISSUE TITLE
Make MVP Set of Assets

### ISSUE THREAD

**Issue by kellishouts** [GomaGames/transmission#47]
just so te can start animating stuff, can you give a complete set of these sized assets?
- **Wizard Level3** all 3 states *Idle*, *Attack*, and *Hit*
- **Staff** sized for battle-mode (i don't have a size for this. can you let me know what the display size is and image size is? (after you size down the wizard, then i figured the weapon size would be determined)
- **Stick** and **Broom Stick** sized for button.
- **Stick** and **Broom Stick** sized for battle-mode.
- **Heart** High Res
- **Coin** High Res

Put in a folder, zip, and attach to this ticket in a comment, then close & let Kelli know.

**Comment by adrian-leon** [comment]
![wizard_c_attack](https://user-images.githubusercontent.com/35876152/35480045-0454e2b2-03bb-11e8-9f17-abc565a78d6b.png)
![wizard_c_hurt](https://user-images.githubusercontent.com/35876152/35480046-04777890-03bb-11e8-9ddf-ea6169c16ed6.png)
![wizard_c_idle](https://user-images.githubusercontent.com/35876152/35480047-048c0d50-03bb-11e8-914f-96f2fcba5402.png)

Let me know if you have any issues with these.

**Comment by adrian-leon** [comment]
![broomstick_attack](https://user-images.githubusercontent.com/35876152/35480050-28be5bd8-03bb-11e8-9d37-843e27f762b1.png)
![staff_attack](https://user-images.githubusercontent.com/35876152/35480051-28d319d8-03bb-11e8-93cf-ee6a5b095f68.png)
![stick_attack](https://user-images.githubusercontent.com/35876152/35480052-28e8bdf6-03bb-11e8-960c-b914dc96b722.png)

**Comment by adrian-leon** [comment]
![broomstick_button](https://user-images.githubusercontent.com/35876152/35480081-f09bab2e-03bb-11e8-980b-3c9fffce65d1.png)
![stick_button](https://user-images.githubusercontent.com/35876152/35480082-f0b0a5a6-03bb-11e8-9a16-1586bc24e35d.png)

**Comment by adrian-leon** [comment]
![coin_icon](https://user-images.githubusercontent.com/35876152/35480117-a06d3e78-03bc-11e8-9572-c314f03b8df4.png)
![heart_icon](https://user-images.githubusercontent.com/35876152/35480118-a07e5c44-03bc-11e8-8d26-7b16493db272.png)

**Comment by adrian-leon** [comment]
[art.zip](https://github.com/GomaGames/transmission/files/1670900/art.zip)

**Comment by adrian-leon** [comment]
Here's the latest folder for the assets, I will try to get more done on these if possible.
[art.zip](https://github.com/GomaGames/transmission/files/1671421/art.zip)

**Comment by kellishouts** [comment]
oh man. >__< i'm sorry if you had to rename a bunch of stuff @fobabett , i was going to fix that for you

**Comment by kellishouts** [comment]
also i changed the naming convention >___< though i'll take a look at where we are at, working on styling now

**Comment by adrian-leon** [comment]
title screen updated for now.
![title_screen](https://user-images.githubusercontent.com/35876152/35487385-d81901f4-042f-11e8-8a4a-f15f1390e494.jpg)

**Comment by adrian-leon** [comment]
![player_lose](https://user-images.githubusercontent.com/35876152/35488083-edeeee28-0437-11e8-8bb6-ff13163af687.jpg)
![player_win](https://user-images.githubusercontent.com/35876152/35488084-ee08f372-0437-11e8-9986-10999aae4a60.jpg)
![player1_screen](https://user-images.githubusercontent.com/35876152/35488085-ee28a794-0437-11e8-9bff-7caf4bddde5e.jpg)
![player2_screen](https://user-images.githubusercontent.com/35876152/35488086-ee41019a-0437-11e8-91d2-4757d8a073d9.jpg)

**Comment by adrian-leon** [comment]
Updated
![titlescreen](https://user-images.githubusercontent.com/35876152/35488182-43cca6ae-0439-11e8-9218-73ecf0abfe57.jpg)
