### ISSUE TITLE
UI : Fix Error in https

### ISSUE THREAD

**Issue by theRemix** [GomaGames/transmission#49]
investigate and fix

works as expected : http://soulcaster.gomagames.com/
security error : https://soulcaster.gomagames.com/

**Comment by fobabett** [comment]
@theRemix I _think_ the server is using ws instead of wss.
according to [this](https://github.com/gorilla/websocket/issues/198), it needs to listen with `http.ListenAndServeTLS` instead of `http.ListenAndServe`

**Comment by theRemix** [comment]
@fobabett yup!
i put a fix here https://github.com/GomaGames/transmission/blob/master/src/TitleScreen/index.js#L6
